
name: focushaven
description: A calming focus timer app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.0.0
  shared_preferences: ^2.1.1
  in_app_purchase: ^3.0.7
  provider: ^6.0.5
  flutter_local_notifications: ^12.0.4
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/focushaven-logo.png
flutterfire configure --project=focushaven-68c59 --platforms=android,ios,macos,weblib/firebase_options.dart
android/app/google-services.json
ios/Runner/GoogleService-Info.plist
macos/Runner/GoogleService-Info.plist
