// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAELrvHA5QKRvlNaHr6ILodulv_LY0Cu7s',
    appId: '1:791775983697:web:1c2da3456a7cb71bb1a070',
    messagingSenderId: '791775983697',
    projectId: 'focushaven-68c59',
    authDomain: 'focushaven-68c59.firebaseapp.com',
    storageBucket: 'focushaven-68c59.firebasestorage.app',
    measurementId: 'G-KPCT4ELB9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEm9gciiUuq-6ExH7bTIZSmoYsqfSMyU',
    appId: '1:791775983697:android:f91f6aa096085832b1a070',
    messagingSenderId: '791775983697',
    projectId: 'focushaven-68c59',
    storageBucket: 'focushaven-68c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_ejiWc0qJYAp2h7_B8PXJFGslpuCO9k',
    appId: '1:791775983697:ios:2ba1a9fff04365c2b1a070',
    messagingSenderId: '791775983697',
    projectId: 'focushaven-68c59',
    storageBucket: 'focushaven-68c59.firebasestorage.app',
    iosBundleId: 'com.example.focushaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_ejiWc0qJYAp2h7_B8PXJFGslpuCO9k',
    appId: '1:791775983697:ios:2ba1a9fff04365c2b1a070',
    messagingSenderId: '791775983697',
    projectId: 'focushaven-68c59',
    storageBucket: 'focushaven-68c59.firebasestorage.app',
    iosBundleId: 'com.example.focushaven',
  );
}
